INSERT INTO especie 
VALUES(0, 'Canídeo', NOW()),
(0,' Felis catus', NOW()),
(0, 'Aves', NOW());


INSERT INTO raca 
VALUES(0, 'Poodle', 1, NOW()),
(0,' Pincher', 1, NOW()),
(0, 'Labrador',1, NOW()),
(0, 'Yorkshire',1, NOW()),
(0, 'Vira-lata',1, NOW()),
(0, 'Shih-Tzu',1, NOW()),
(0, 'Lhasa Apso',1, NOW()),
(0, 'Buldogue Francês',1, NOW()),
(0, 'Maltês',1, NOW()),
(0, 'Golden Retriever',1, NOW()),
(0, 'Pug',1, NOW()),
(0, 'Dachshund',1, NOW()),
(0, 'Spitz Alemão',1, NOW()),
(0, 'Schnauzer',1, NOW()),
(0, 'Beagle',1, NOW()),
(0, 'Cocker Spaniel',1, NOW()),
(0, 'Border Collie',1, NOW()),
(0, 'Buldogue Inglês',1, NOW()),
(0, 'Pit Bull',1, NOW()),
(0, 'Chow Chow',1, NOW()),
(0, 'Rottweiler',1, NOW()),
(0, 'Persa',2, NOW()),
(0, 'Siamês',2, NOW()),
(0, 'Himalaia',2, NOW()),
(0, 'Maine Coon',2, NOW()),
(0, 'Angorá',2, NOW()),
(0, 'Persa',2, NOW()),
(0, 'Siberiano',2, NOW()),
(0, 'Sphynx',2, NOW()),
(0, 'Burmese',2, NOW()),
(0, 'Ragdoll',2, NOW()),
(0, 'British Shorthair',2, NOW());